// src/data/propertyData.js
const propertyData = [
    {
        id: 1,
        type: "Land with old house",
        landArea: "3600 sqft",
        landSize: " 60 x 60 ",
        address: " Jayalalithaa street, Kanathur, Very nearer to ECR road,Chennai",
        features: "1.5 grounds, (3/4+3/4), 20' road, east facing, near beach, compound wall, gate 2 Nos, dead end, power 3 phase, panchayat board water supply, un approved.",
        ageOfProperty: "Land",
        buildingarea: "No Value",
        groundFloor: "-",
        firstFloor: "-",
        secondFloor: "-",
        location: "ECR , Chennai",
        furnished: "-",
        status: <span className="badge fw-light bg-success">Available</span>,
        rentOrSale: "Sale",
        rate: "2 Cr (Negotiable)"
    },
    {
        id: 2,
        type: "Land with old house",
        landArea: " 2400 sqft",
        landSize: "40 x 60",
        address: "No.2, pugalenthi street Durga Nagar, near Mepz, Chrompet,Chennai.",
        features: "Near Chrompet Railway station, old building with good conditionWater, EB, clear title",
        buildingarea: "Old house, (No value) 1200 sqft",
        ageOfProperty: "20 Years",
        groundFloor: "-",
        firstFloor: "-",
        secondFloor: "-",
        location: "Chrompet , Chennai",
        furnished: "Old House",
        status: <span className="badge fw-light bg-success">Available</span>,
        rentOrSale: "Sale",
        rate: "1.20 Cr (Negotiable)"
    },

    {
        id: 3,
        type: "Individual Bungalow",
        landArea: "5110 sqft",
        landSize: "70 x 73",
        features: "5 bedrooms with attached toilets, wardrobe, office Room, gym room, gents sitting, ladies sitting, private hall, meditation hall in terrace (West facing)",
        address: "Devaraj nagar, Sholinganallur to ECR road",
        buildingarea: "6200 sqft",
        ageOfProperty: "9 years",
        groundFloor: "-",
        firstFloor: "-",
        secondFloor: "-",
        location: "Sholinganallur , Chennai",
        furnished: "Semi-Furnished",
        status: <span className="badge fw-light bg-success">Available</span>,
        rentOrSale: "Rent / Sale",
        rate: " 1.5 L Per Month / 6 Cr (Negotiable)"

    },
    {
        id: 4,
        type: "Flats",
        address: "Annanagar, Chindamani back side, VOC Nagar,1st Floor(Roadside flat available with 4 balconies, Flat area 855 sq ft (UDS 486 sq ft)),2nd Floor(Roadside flat and backside flat available, Roadside flat size 855 sq ft (UDS 486 sq ft), Back Side Flat size 718 sq ft (UDS 407 sq ft))",
        features: "New House flat, Only two-wheeler parking",
        landArea: "2220 sq ft",
        landSize: "70 x 73",
        buildingarea: "-",
        ageOfProperty: "-",
        groundFloor: "-",
        firstFloor: "-",
        secondFloor: "-",
        location: "VOC Nagar , Chennai",
        furnished: "-",
        status: <span className="badge fw-light bg-success">Available</span>,
        rentOrSale: "Sale",
        rate: "9000/- negotiable (Prevailing rate now in Anna Nagar Rs.12000/- and above)"
    },
    {
        id: 5,
        type: "Flats",
        landArea: "2510 sq.ft",
        landSize: "Flat F2, 1210 sq feet (UDS 583 sq ft)",
        address: "Balamurugan garden, opp to big park, OMR, Okkiyam Thuraipakkam",
        features: "1BHK with Lift, Car parking, In ground floor guest house available",
        buildingarea: "4000 sq.ft",
        ageOfProperty: "9 years old (For sale)",
        groundFloor: "-",
        firstFloor: "-",
        secondFloor: "-",
        location: "Thuraipakkam , Chennai",
        furnished: "-",
        status: <span className="badge fw-light bg-success">Available</span>,
        rentOrSale: "-",
        rate: "-"
    },
    {
        id: 6,
        type: "Land and building",
        landArea: "2 Grounds",
        landSize: "17.5 x 10 ft entrance, and inside hall type, veg hotel was running,",
        address: "Ranganathan street, T.Nagar, chennai-17",
        features: "near mambalam railway station, Ranganathan street market, textile shops, jewelry shops, best for hotel, lodging, godown, shopping complex,etc, rent income property",
        buildingarea: "old building, 5000 sqft, rooftop covered shed,",
        ageOfProperty: "20 years",
        location: "T.Nagar, Chennai",
        furnished: "Yes",
        status: <span className="badge fw-light bg-success">Available</span>,
        rentOrSale: "Sale",
        rate: "25 Cr Negotiable"
    },
    {
        id: 7,
        type: "New Flat House (Consider it as a separate bungalow)",
        landArea: "900 sqft",
        landSize: "23 x 30 , 6 x 30",
        address: "Nandanam, near chamiers road, near cenotaph road, near moopanar flyover.",
        features: "new construction, 30'road, Car parking, near Apollo hospital, Teynanpet, rental income property.",
        buildingarea: "2700 sqft",
        ageOfProperty: "New",
        location: "Teynampet , Chennai",
        furnished: "Semi-Furnished,New Flat",
        status: <span className="badge fw-light bg-success">Available</span>,
        rentOrSale: "Sale",
        rate: " 10000/- per sqft (Nearby now prevailing rate is 12000/- but ready to give for Rs.10000/-)"

    },
    // Add more properties as needed
];

export default propertyData;
